resolver: lts-11.22
extra-deps:
  - distributed-process-0.7.4
  - distributed-process-client-server-0.2.5.1
  - distributed-process-extras-0.3.5
  - network-transport-0.5.2
  - network-transport-tcp-0.6.0
  - distributed-process-async-0.2.6
  - distributed-process-simplelocalnet-0.2.4
  - syb-0.7
packages:
- .
